package com.bjpowernode.crm.workbench.mapper;

import com.bjpowernode.crm.workbench.domain.Activity;
import com.bjpowernode.crm.workbench.domain.Clue;
import com.bjpowernode.crm.workbench.domain.ClueActivityRelation;
import com.bjpowernode.crm.workbench.domain.ClueRemark;

import java.util.List;
import java.util.Map;

public interface ClueMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_clue
     *
     * @mbggenerated Sat Sep 23 15:31:18 CST 2023
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_clue
     * 
     * @mbggenerated Sat Sep 23 15:31:18 CST 2023
     */
    int insert(Clue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_clue
     *
     * @mbggenerated Sat Sep 23 15:31:18 CST 2023
     */
    int insertSelective(Clue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_clue
     *
     * @mbggenerated Sat Sep 23 15:31:18 CST 2023
     */
    Clue selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_clue
     *
     * @mbggenerated Sat Sep 23 15:31:18 CST 2023
     */
    int updateByPrimaryKeySelective(Clue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_clue
     *
     * @mbggenerated Sat Sep 23 15:31:18 CST 2023
     */
    int updateByPrimaryKey(Clue record);
    List<Clue> selectAllClues();

    int deleteClueActivityRelationByClueIDActivityId(ClueActivityRelation clueActivityRelation);
    List<Clue> selectClueByConditionForPagination(Map<String, Object> map);
    int selectTotalRowsByConditionForPagination(Map<String, Object> map);
    int insertSaveCreateClue(Clue clue);
    Clue selectClueDetailInfoById(String id);
    Clue selectClueInfoForConvert(String id);
    int deleteClueForConvert(String clueId);
}